### ISSUE TITLE
Provando a compilare ed eseguire dà errore

### ISSUE THREAD

**Issue by pierol** [jiayihu/vecomp-redux#1]
`zone.js:522 Unhandled Promise rejection: Cannot read property 'apply' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'apply' of null
    at compose.js:32
    at NgRedux.configureStore (ng-redux.js:93)
    at new AppModule (app.module.ts:30)
    at AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:159)
    at AppModuleInjector.NgModuleInjector.create (ng_module_factory.js:123)
    at NgModuleFactory.create (ng_module_factory.js:91)
    at application_ref.js:342
    at ZoneDelegate.webpackJsonp.613.ZoneDelegate.invoke (zone.js:334)
    at Object.onInvoke (ng_zone.js:273)
    at ZoneDelegate.webpackJsonp.613.ZoneDelegate.invoke (zone.js:333)
    at Zone.webpackJsonp.613.Zone.run (zone.js:126)
    at NgZone.run (ng_zone.js:142)
    at PlatformRef_._bootstrapModuleFactoryWithZone (application_ref.js:340)
    at application_ref.js:391
    at ZoneDelegate.webpackJsonp.613.ZoneDelegate.invoke (zone.js:334) TypeError: Cannot read property 'apply' of null
    at http://localhost:4200/vendor.bundle.js:60793:12
    at NgRedux.configureStore (http://localhost:4200/vendor.bundle.js:21377:131)
    at new AppModule (http://localhost:4200/main.bundle.js:109:17)
    at AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:159:24)
    at AppModuleInjector.NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:54584:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:54552:18)
    at http://localhost:4200/vendor.bundle.js:36831:61
    at ZoneDelegate.webpackJsonp.613.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2612:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:27243:37)
    at ZoneDelegate.webpackJsonp.613.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2611:32)
    at Zone.webpackJsonp.613.Zone.run (http://localhost:4200/polyfills.bundle.js:2404:43)
    at NgZone.run (http://localhost:4200/vendor.bundle.js:27112:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:4200/vendor.bundle.js:36829:23)
    at http://localhost:4200/vendor.bundle.js:36880:59
    at ZoneDelegate.webpackJsonp.613.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2612:26)`

**Comment by pierol** [comment]
Dovrei aver risolto bisogna installare l'estensione Redux di Chrome sennò da errore

**Comment by jiayihu** [comment]
Ciao, grazie per la segnalazione! Risolto in https://github.com/jiayihu/vecomp-redux/commit/a3ad7c72b728a43c421c260485f7a8c64b8b4701
